export enum SendSockEvent {
  DISCONNECTED="DISCONNECTED",
  START="START",
  STOP="STOP",
  RESET="RESET",
  SET_POWER="SET_POWER",
  GET_POWER="GET_POWER",
  SET_BEEP="SET_BEEP",
  GET_BEEP="GET_BEEP",
  EXIT="EXIT",
}